---
- name: Install a list of packages
  yum:
    name:
      - nginx
    state: present

- name: Hello
  shell: whoami
  register: whoami_out
  args:
    executable: /bin/bash

- name: Just checking the exit code 
  debug:
    msg: "{{ whoami_out }}"

- name: create file
  file:
    path: "~/{{file_name}}.txt"
    state: "touch"
    
- name: start nginx svc
  service:
    name: nginx
    state: started
