---
- name: Install a list of packages
  yum:
    name:
      - nginx
    state: present

- name: Hello
  ansible.builtin.shell: whoami > whoami.txt
  args:
    executable: /bin/bash
    
- name: start nginx svc
  service:
    name: nginx
    state: started

- name: create file
  file:
    path: "~/{{file_name}}.txt"
    state: "touch"
